import "./globals.css";
import {Inter} from "next/font/google";
import Headers from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import {Toaster} from "sonner"

const inter= Inter({subsets:["latin"]});

export const metadata = {
  title: "Perfina: One stop personal Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html suppressHydrationWarning lang="en" className={inter.className}>
      <body 
      style={{ marginTop: 0 }}>
          {/* Header */}
          <Headers/>
          <main className="min-h-screen">{children}</main>
          <Toaster richcolors/>
          {/* Footer */}
          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p> &copy;  2025 | Made by Divyansh Jain. </p>
            </div>
          </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
